name: Container Build

on:
  push:
    branches:
      - self-host
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build Container
        uses: ./.github/actions/build-container
        with:
          version: "develop"
          push_containers: "true"
          create_release: "false"
          registry_user: ${{ secrets.DOCKER_HUB_USER }}
          registry_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          release_access_token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
